#:schema node_modules/wrangler/config-schema.json
name = "http-waifus"
compatibility_date = "2025-11-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#r2-buckets
[[r2_buckets]]
binding = "MEDIA"
bucket_name = "http-waifus-media"
